### ISSUE TITLE
Global Leaderboard

### ISSUE THREAD

**Issue by nimi2356** [AndrewFriery/CSCI3308-011-02#8]
As a user, I want to be able to go to a global leaderboard page and view a descending list of users and their high scores for the game.

Acceptance Criteria: Press a button on the navbar to load the global leaderboard page which will display users and their high scores for the game.

**Comment by ivonpechmann** [comment]
Checklist:
- Access user table and display in descending order by high score
- CSS styling
- Display username and score for each user
- Make it dynamically updating so that it stays up to date with users and scores
